CREATE TABLE Items(
	ItemID INT NOT NULL,
	Name VARCHAR(50),
	Currently  DECIMAL(8,2),
	Buy_Price  DECIMAL(8,2),
	First_Bid  DECIMAL(8,2),
	Num_Bids INT,
	Latitude DOUBLE(11,8),
	Longitude DOUBLE(11,8),
	Location VARCHAR(4000),
	Country VARCHAR(200),
	Started TIMESTAMP,
	Description VARCHAR(4000),
	PRIMARY KEY (ItemID)
);

CREATE TABLE Item_Category(
	ItemID INT NOT NULL,
	Category VARCHAR(200),
	PRIMARY KEY(ItemID,Category)
);

CREATE TABLE Users(
	UID VARCHAR(767) NOT NULL,
	Location VARCHAR(4000),
	Country VARCHAR(200),
	Bidder_Rating INT,
	Seller_Rating INT,
	PRIMARY KEY (UID)
);

CREATE TABLE Bids(
	ItemID INT NOT NULL,
	UID VARCHAR(767) NOT NULL,
	Time TIMESTAMP,
	Amount DECIMAL(8,2),
	PRIMARY KEY(ItemID,UID,Time)
);

LOAD DATA LOCAL INFILE '~/project2/items.dat' INTO TABLE Items
FIELDS TERMINATED BY '|*|' OPTIONALLY ENCLOSED BY '"';

LOAD DATA LOCAL INFILE '~/project2/item_category.dat' INTO TABLE Item_Category
FIELDS TERMINATED BY '|*|';

LOAD DATA LOCAL INFILE '~/project2/users.dat' INTO TABLE Users
FIELDS TERMINATED BY '|*|' OPTIONALLY ENCLOSED BY '"';

LOAD DATA LOCAL INFILE '~/project2/bids.dat' INTO TABLE Bids
FIELDS TERMINATED BY '|*|';




