LOAD DATA LOCAL INFILE 'items.dat' INTO TABLE Items
FIELDS TERMINATED BY '|*|';

LOAD DATA LOCAL INFILE 'item_category.dat' INTO TABLE Item_Category
FIELDS TERMINATED BY '|*|';

LOAD DATA LOCAL INFILE 'users.dat' INTO TABLE Users
FIELDS TERMINATED BY '|*|';

LOAD DATA LOCAL INFILE 'bids.dat' INTO TABLE Bids
FIELDS TERMINATED BY '|*|';